// Optimize: load used icons only

import 'vue-awesome/icons/ban'
import 'vue-awesome/icons/calendar-check'
import 'vue-awesome/icons/check'
import 'vue-awesome/icons/chevron-down'
import 'vue-awesome/icons/chevron-right'
import 'vue-awesome/icons/chevron-up'
import 'vue-awesome/icons/circle'
import 'vue-awesome/icons/compress'
import 'vue-awesome/icons/copy'
import 'vue-awesome/icons/download'
import 'vue-awesome/icons/edit'
import 'vue-awesome/icons/expand'
import 'vue-awesome/icons/external-link-alt'
import 'vue-awesome/icons/history'
import 'vue-awesome/icons/lightbulb'
import 'vue-awesome/icons/minus'
import 'vue-awesome/icons/plus'
import 'vue-awesome/icons/plus-circle'
import 'vue-awesome/icons/regular/bookmark'
import 'vue-awesome/icons/regular/eye-slash'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/sync'
import 'vue-awesome/icons/times'
import 'vue-awesome/icons/upload'
import 'vue-awesome/icons/user'
